server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54326/event
    username: postgres
    password: postgres

logging:
  level:
    root: info
  config: classpath:logback-dev.xml

log:
  destination: 127.0.0.1